language: python
python:
  - "3.4"
  - "3.5"
  - "3.5-dev" # 3.5 development branch
  - "nightly" # currently points to 3.6-dev
#  - "pypy3"
# command to install dependencies
install:
  - "pip install -r requirements.txt"
  - "pip install codecov"
# command to run tests
script:
  - "python setup.py test"

after_success:
  - bash <(curl -s https://codecov.io/bash)